name: pagarme_flutter_card_hash
description: A Flutter package that allows you to generate card hashes to be used with Pagar.me's payment platform.
version: 0.2.0
homepage: https://github.com/caws/pagarme_flutter_card_hash

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  encrypt: ^5.0.1
  dio: ^4.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: